# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180626_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfo',
            options={'verbose_name': '武侠小说', 'verbose_name_plural': '武侠小说'},
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img', verbose_name='封面'),
            preserve_default=False,
        ),
    ]
