# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_auto_20180627_2241'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookinfo',
            managers=[
            ],
        ),
    ]
